### ISSUE TITLE
No such file or directory: '/shared/results/ikostiuk/datasets/polygen_exports'

### ISSUE THREAD

**Issue by delldu** [KostiukIvan/PolyGen#4]
Dear friend,
Thank you for your good job !
Now we meet a little trouble, that is we run the following command:
`python experiments/main.py `

Got the following error:
```
  File "/media/dell/02a3d71a-295d-455b-9038-2d915c35d598/Workspace/debug/PolyGen/experiments/main.py", line 43, in <module>
    training_data = dl.VerticesDataset(root_dir="/shared/results/ikostiuk/datasets/polygen_exports",
  File "/media/dell/02a3d71a-295d-455b-9038-2d915c35d598/Workspace/debug/PolyGen/data_utils/dataloader.py", line 43, in __init__
    for class_idx, class_name in enumerate(os.listdir(root_dir)):
FileNotFoundError: [Errno 2] No such file or directory: '/shared/results/ikostiuk/datasets/polygen_exports'
```
How to fix this problem ?

Best regards,

**Comment by KostiukIvan** [comment]
Hi @delldu, 
Thank you for reaching out. 
You need to generate a dataset.
To achieve it use please following script: `https://github.com/KostiukIvan/PolyGen/blob/main/blender/create_polygen_dataset.py` and shapenet dataset: `https://shapenet.org/` 
Best regards

**Comment by delldu** [comment]
Many thanks @KostiukIvan
